id: bitmovin-video
displayName: Bitmovin
description: |
  Bitmovin empowers businesses to expand their viewer reach and stream video globally with unmatched reliability, scalability, and the highest quality across the broadest range of devices.
icon: logo.svg
install:
  primary:
    nerdlet: 
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: bitmovin-video
        frameworkConfigId: bitmovin-video
      requiresAccount: false
keywords:
  - bitmovin
  - video quality
  - video experience
  - quality of experience
  - video streaming
  - video metrics
  - featured
  - newrelic partner
  - NR1_addData
categoryTerms:
  - newrelic partner
